#!/usr/bin/env python

# The main entry point. This is called from a ROS-enabled 
# machine by
# 
# roslaunch luxagent luxagent.py
#

from luxagent import main

if __name__== '__main__':
     main()

#import agent_logic.main
#agent_logic.main.main()
