#!/usr/bin/env python

# The main entry point. This is called from a ROS-enabled 
# machine by
# 
# roslaunch luxagent luxagent.py
#

from config import get_config_value
from subprocess import call

if __name__== '__main__':
	autoupdate = get_config_value('autoupdate')
	print "Autoupdate", autoupdate
	if autoupdate=='true':
		print "Will call update here..."
	else:
		print "Skip update (autoupdate in config.txt is not 'true')"	
	from luxagent import main
	main()
