#!/usr/bin/env python

# The main entry point. This is called from a ROS-enabled 
# machine by
# 
# roslaunch luxagent luxagent.py
#

from config import get_config_value
from subprocess import call

if __name__== '__main__':
	print get_config_value('autoupdate')
	from luxagent import main
    main()
