#!/usr/bin/env python

# This script updates to the latest version of the luxagent code
# on github. The branch used is 'distribution'.

def main(argv):
	print "Running update script"

	# See if we need to pass on next script option to pull.sh
	next_script = None
	next_file_option = '-n'
	try:
		opts, args = getopt.getopt(argv,"hn:")
	except getopt.GetoptError:
		print 'Error in parameters:'
		print 'update'
		print 'update -n <next script>'
		sys.exit(2)
	for opt, arg in opts:
		if opt == '-h':
			print 'Update Utility for Luxagent'
			print 'Options:'
			print '-h Print help'
			print next_file_option + ' <script> Next script to run.'
		elif opt == next_file_option:
			next_script = arg

	# Where are we?
	script_dir, filename = os.path.split(sys.argv[0])
	cwd = os.getcwd()
	pull = "pull"
	pull_default = "pull-default"
	pull_pathname = script_dir + "/" + pull
	pull_default_pathname = script_dir + "/" + pull_default
	pull_exists = os.path.isfile(pull_pathname)

	# Copy pull-default.sh to pull.sh if it doesn't already exist
	print "Checking for existence of", pull_pathname, pull_exists 
	if pull_exists == True:
		print pull + " already exists"
	else:	
		print "Copying " + pull_default + " to " + pull
		call(["cp", pull_default_pathname, pull_pathname])

	# Chain pull.sh
	print "Next script:", next_script
	if next_script != None:
		print "Chaining pull with option -n", next_script
	else:
		print "Chaining pull with no options"

if __name__ == "__main__":
   main(sys.argv[1:])

