#!/usr/bin/env python

# This script updates to the latest version of the luxagent code
# on github. The branch used is 'distribution'.

import os
import sys
from subprocess import call, Popen

def update():
	script_dir, filename = os.path.split(sys.argv[0])
	base_dir = script_dir + "/.."

	print "Configuring git"
	call(['git', 'config', 'user.email', 'foo@bar.com'], cwd=base_dir)
	print "git fetch --all"
	call(['git', 'fetch', '--all'], cwd=base_dir)
	print "git reset --hard origin/distribution"
	call(['git', 'reset', '--hard', 'origin/distribution'], cwd=base_dir)
	print "Executing in", base_dir
	print "waiting..."
	call(['cat','src/luxagent/version.py'], cwd=base_dir)

if __name__== '__main__':
	#print "Current version", luxagent.version()
	update()
	import luxagent
	print "Running version", luxagent.version()
	#luxagent.main()
