#!/usr/bin/env python

# This script updates to the latest version of the luxagent code
# on github. The branch used is 'distribution'.

import os
import sys
from subprocess import call, Popen
import luxagent

def update():
	script_dir, filename = os.path.split(sys.argv[0])
	base_dir = script_dir + "/.."


	#process = Popen(['git', 'pull', 'origin', 'distribution'], cwd=base_dir, stdout=PIPE, stderr=STDOUT)
	print "Executing in", base_dir
	process = Popen(['git', 'pull', 'origin', 'distribution'], cwd=base_dir)
	#process = Popen(['git', 'status'], cwd=base_dir)
	process.wait()
	print "stdout:"
	print process.stdout
	print "return code", process.returncode

if __name__== '__main__':
	print "Current version", luxagent.version()
	update()
	reload(luxagent)
	print "Running version", luxagent.version()
	#luxagent.main()
